// metrics-sim emits realistic Prometheus metrics that match the Sympozium
// Grafana dashboard queries. Deploy alongside the showcase to populate
// dashboards with live data.
package main

import (
	"fmt"
	"log"
	"math"
	"math/rand"
	"net/http"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

var (
	models    = []string{"gemini-2.5-pro", "gemini-2.5-flash", "gemma-3-27b-it"}
	instances = []string{"prod-main", "staging", "dev-sandbox"}
	tools     = []string{"kubectl", "gcloud", "gsutil", "bq", "curl"}
	statuses  = []string{"success", "failed"}

	agentRuns = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "sympozium_agent_runs_total",
		Help: "Total agent runs by status, model, and instance",
	}, []string{"status", "model", "instance_name"})

	agentRunDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "sympozium_agent_run_duration",
		Help:    "Agent run duration in milliseconds",
		Buckets: []float64{100, 250, 500, 1000, 2500, 5000, 10000, 30000, 60000, 120000},
	}, []string{"model"})

	inputTokens = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "gen_ai_usage_input_tokens_total",
		Help: "Input tokens consumed by model",
	}, []string{"model"})

	outputTokens = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "gen_ai_usage_output_tokens_total",
		Help: "Output tokens generated by model",
	}, []string{"model"})

	gatewayReady = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "sympozium_gateway_ready",
		Help: "Whether the gateway is ready (1=ready, 0=not ready)",
	})

	toolInvocations = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "sympozium_tool_invocations_total",
		Help: "Tool invocations by tool name and status",
	}, []string{"tool", "status"})

	skillDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "sympozium_skill_duration",
		Help:    "Skill sidecar execution duration in milliseconds",
		Buckets: []float64{50, 100, 250, 500, 1000, 2500, 5000, 10000},
	}, []string{"skill"})

	errorsTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "sympozium_errors_total",
		Help: "Total unhandled errors",
	})

	webEndpointServing = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "sympozium_web_endpoint_serving",
		Help: "Whether the web endpoint is serving (1=yes)",
	})

	webEndpointGatewayNotReady = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "sympozium_web_endpoint_gateway_not_ready_total",
		Help: "Gateway not-ready events",
	})

	webEndpointRouteCreated = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "sympozium_web_endpoint_route_created_total",
		Help: "Route creation events",
	})
)

func init() {
	prometheus.MustRegister(
		agentRuns, agentRunDuration, inputTokens, outputTokens,
		gatewayReady, toolInvocations, skillDuration, errorsTotal,
		webEndpointServing, webEndpointGatewayNotReady, webEndpointRouteCreated,
	)
}

func main() {
	log.Println("metrics-sim: starting Sympozium metrics simulator on :9090")

	// Set gauges to healthy state
	gatewayReady.Set(1)
	webEndpointServing.Set(1)
	webEndpointRouteCreated.Add(3) // 3 routes created at startup

	go simulateTraffic()

	http.Handle("/metrics", promhttp.Handler())
	http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprintln(w, "ok")
	})
	log.Fatal(http.ListenAndServe(":9090", nil))
}

func simulateTraffic() {
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()

	hour := 0.0
	for range ticker.C {
		hour += 5.0 / 3600.0 // advance simulated hour

		// Diurnal pattern: more traffic during "business hours"
		diurnal := 0.5 + 0.5*math.Sin(hour*2*math.Pi/24-math.Pi/2)
		baseRate := 2.0 + 6.0*diurnal // 2-8 runs per tick

		// Simulate agent runs
		numRuns := int(baseRate) + rand.Intn(3)
		for i := 0; i < numRuns; i++ {
			model := models[weightedChoice([]float64{0.55, 0.35, 0.10})]
			instance := instances[weightedChoice([]float64{0.60, 0.25, 0.15})]

			// 5% failure rate for pro, 2% for flash, 8% for gemma
			failRates := map[string]float64{
				"gemini-2.5-pro":   0.05,
				"gemini-2.5-flash": 0.02,
				"gemma-3-27b-it":   0.08,
			}
			status := "success"
			if rand.Float64() < failRates[model] {
				status = "failed"
				errorsTotal.Inc()
			}

			agentRuns.WithLabelValues(status, model, instance).Inc()

			// Duration: flash is faster, gemma is slower
			baseDuration := map[string]float64{
				"gemini-2.5-pro":   3000,
				"gemini-2.5-flash": 800,
				"gemma-3-27b-it":   5000,
			}
			duration := baseDuration[model] * (0.5 + rand.Float64())
			agentRunDuration.WithLabelValues(model).Observe(duration)

			// Tokens: proportional to duration
			inTokens := float64(200 + rand.Intn(1800))
			outTokens := float64(100 + rand.Intn(900))
			if model == "gemini-2.5-flash" {
				outTokens *= 0.6 // flash generates less
			}
			inputTokens.WithLabelValues(model).Add(inTokens)
			outputTokens.WithLabelValues(model).Add(outTokens)
		}

		// Simulate tool invocations (1-4 per tick)
		numTools := 1 + rand.Intn(4)
		for i := 0; i < numTools; i++ {
			tool := tools[rand.Intn(len(tools))]
			toolStatus := "success"
			if rand.Float64() < 0.03 { // 3% tool error rate
				toolStatus = "error"
			}
			toolInvocations.WithLabelValues(tool, toolStatus).Inc()

			// Skill durations
			skillDur := 200.0 + rand.Float64()*2000
			skillDuration.WithLabelValues(tool).Observe(skillDur)
		}

		// Rare gateway blip (0.1% chance per tick)
		if rand.Float64() < 0.001 {
			gatewayReady.Set(0)
			webEndpointGatewayNotReady.Inc()
			// Recover after next tick
			go func() {
				time.Sleep(10 * time.Second)
				gatewayReady.Set(1)
			}()
		}
	}
}

func weightedChoice(weights []float64) int {
	total := 0.0
	for _, w := range weights {
		total += w
	}
	r := rand.Float64() * total
	cumulative := 0.0
	for i, w := range weights {
		cumulative += w
		if r <= cumulative {
			return i
		}
	}
	return len(weights) - 1
}
